IntegrateWithTFSAndCheckInAutomatically: true
ProfileNames:
  - ACCOUNTING
  - ACQUIRING_2
  - ACQUIRING_KERNEL
  - BATCH_EMBOSS
  - CARD_APPLICATION
  - CARD_PAYMENT
  - CLEARING_COMMON
  - CRD_INSTANT
  - SWITCH_BKM
  - SYS_OPERATION
  - TMS2
  - VISA_MANAGEMENT_2
  - CC_OPERATIONS
  - CC_OPERATIONS_KERNEL
  - DLV_COURIER
  - CreditCardStatement
  - MASTERCARD_MANAGEMENT
  - Dispute
  - Collection
  - ParameterManagement
  - CreditCardLegalFollowup
  - CreditCardLifecycle
  - CreditCardIssuing
  - CreditCardStatementBatch
  - CreditCardTransaction
  - CreditCardLimit
  - EMB_BATCH
  - CRD_BATCH
  - '*'
SchemaNames:
  - BKM
  - BNS
  - CCA
  - CFG
  - CIS
  - CLR
  - COR
  - CRD
  - DBT
  - DIS
  - DLV
  - EMB
  - EMC
  - EMV
  - ESW
  - FRD
  - KMT
  - MRC
  - POS
  - PPD
  - PRM
  - RKL
  - STK
  - STM
  - SWC
  - SYSOP
  - TMS
  - TRN
  - VIS
  - '*'